services:
  user_service:
    url: http://localhost:8080
    timeout: 5
  project_service:
    url: http://localhost:8080
    timeout: 5
  navigation_service:
    url: http://localhost:8080
    timeout: 5
  delegation_service:
    url: http://localhost:8080
    timeout: 5
  notification_service:
    url: http://localhost:8080
    timeout: 5

gateway:
  url: http://localhost:8080
