# docker-compose.yml
version: '3.8'

services:
  gateway:
    build: .
    container_name: api_gateway
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
